x0 = [120, 120, 120]
lam = [0.01, 0.01, 0.0]
mu = [0.01, 0.01, 0.01]
C = [1.0, 1.0]  # capacity of servers 1, 2
c = [1.0, 1.0, 1.0]  # hold cost per item per unit time
G = [[1.0, 0, 0], [0, 1.0, 0], [0, -1.0, 1.0]]
